#include "DesignTop_sim.h"
#include <thread>

using namespace bsim;

#define SIGN_EXTEND(start, end, x) (((x) & ((1ULL << (start)) - 1)) | (((x) & (1ULL << ((start) - 1))) ? (((1ULL << ((end) - (start))) - 1) << (start)) : 0))

#define MASK(width, expr) (((1ULL << (width)) - 1) & ((expr)))

void simulate_0( circuit_state* state ) {

// Variable declarations

// Internal variables
uint16_t  sub_671_673_674_out;
uint16_t  lb_padded_2_stencil_update_stream$mem_2$zero_const_out;
uint16_t  lb_padded_2_stencil_update_stream$mem_2$max_const_out;
uint16_t  lb_padded_2_stencil_update_stream$mem_2$c1_out;
uint16_t  lb_padded_2_stencil_update_stream$mem_2$add_w_out;
uint8_t  lb_padded_2_stencil_update_stream$mem_2$waddr_eq_out;
uint16_t  lb_padded_2_stencil_update_stream$mem_2$waddr_mux_out;
uint8_t  lb_padded_2_stencil_update_stream$mem_2$veq_out;
uint16_t  sub_629_631_632_out;
uint16_t  lb_padded_2_stencil_update_stream$mem_2$add_r_out;
uint8_t  lb_padded_2_stencil_update_stream$mem_2$raddr_eq_out;
uint16_t  lb_padded_2_stencil_update_stream$mem_2$raddr_mux_out;
uint16_t  lb_padded_2_stencil_update_stream$mem_1$zero_const_out;
uint8_t  lb_padded_2_stencil_update_stream_wen_out;
uint16_t  lb_padded_2_stencil_update_stream$mem_2$waddr$enMux_out;
uint16_t  lb_padded_2_stencil_update_stream$mem_2$raddr$enMux_out;
uint16_t  lb_padded_2_stencil_update_stream$mem_1$max_const_out;
uint16_t  lb_padded_2_stencil_update_stream$mem_1$c1_out;
uint16_t  lb_padded_2_stencil_update_stream$mem_1$add_w_out;
uint8_t  lb_padded_2_stencil_update_stream$mem_1$waddr_eq_out;
uint16_t  lb_padded_2_stencil_update_stream$mem_1$waddr_mux_out;
uint16_t  lb_padded_2_stencil_update_stream$mem_1$waddr$enMux_out;
uint8_t  lb_padded_2_stencil_update_stream$mem_1$veq_out;
uint16_t  lb_padded_2_stencil_update_stream$mem_1$add_r_out;
uint8_t  lb_padded_2_stencil_update_stream$mem_1$raddr_eq_out;
uint16_t  lb_padded_2_stencil_update_stream$mem_1$raddr_mux_out;
uint16_t  lb_padded_2_stencil_update_stream$mem_1$raddr$enMux_out;
uint16_t  lb_p3_cim_stencil_update_stream$mem_2$zero_const_out;
uint16_t  lb_p3_cim_stencil_update_stream$mem_2$max_const_out;
uint16_t  lb_p3_cim_stencil_update_stream$mem_2$c1_out;
uint16_t  lb_p3_cim_stencil_update_stream$mem_2$add_w_out;
uint8_t  lb_p3_cim_stencil_update_stream$mem_2$waddr_eq_out;
uint16_t  lb_p3_cim_stencil_update_stream$mem_2$waddr_mux_out;
uint8_t  lb_p3_cim_stencil_update_stream$mem_2$veq_out;
uint16_t  lb_p3_cim_stencil_update_stream$mem_2$add_r_out;
uint8_t  lb_p3_cim_stencil_update_stream$mem_2$raddr_eq_out;
uint16_t  lb_p3_cim_stencil_update_stream$mem_2$raddr_mux_out;
uint16_t  lb_p3_cim_stencil_update_stream$mem_1$zero_const_out;
uint8_t  lb_p3_cim_stencil_update_stream_wen_out;
uint16_t  lb_p3_cim_stencil_update_stream$mem_2$waddr$enMux_out;
uint16_t  lb_p3_cim_stencil_update_stream$mem_2$raddr$enMux_out;
uint16_t  lb_p3_cim_stencil_update_stream$mem_1$max_const_out;
uint16_t  lb_p3_cim_stencil_update_stream$mem_1$c1_out;
uint16_t  lb_p3_cim_stencil_update_stream$mem_1$add_w_out;
uint8_t  lb_p3_cim_stencil_update_stream$mem_1$waddr_eq_out;
uint16_t  lb_p3_cim_stencil_update_stream$mem_1$waddr_mux_out;
uint16_t  lb_p3_cim_stencil_update_stream$mem_1$waddr$enMux_out;
uint8_t  lb_p3_cim_stencil_update_stream$mem_1$veq_out;
uint16_t  lb_p3_cim_stencil_update_stream$mem_1$add_r_out;
uint8_t  lb_p3_cim_stencil_update_stream$mem_1$raddr_eq_out;
uint16_t  lb_p3_cim_stencil_update_stream$mem_1$raddr_mux_out;
uint16_t  lb_p3_cim_stencil_update_stream$mem_1$raddr$enMux_out;
uint16_t  lb_grad_yy_2_stencil_update_stream$mem_2$zero_const_out;
uint16_t  lb_grad_yy_2_stencil_update_stream$mem_2$max_const_out;
uint16_t  lb_grad_yy_2_stencil_update_stream$mem_2$c1_out;
uint16_t  lb_grad_yy_2_stencil_update_stream$mem_2$add_w_out;
uint8_t  lb_grad_yy_2_stencil_update_stream$mem_2$waddr_eq_out;
uint16_t  lb_grad_yy_2_stencil_update_stream$mem_2$waddr_mux_out;
uint8_t  lb_grad_yy_2_stencil_update_stream$mem_2$veq_out;
uint16_t  lb_grad_yy_2_stencil_update_stream$mem_2$add_r_out;
uint8_t  lb_grad_yy_2_stencil_update_stream$mem_2$raddr_eq_out;
uint16_t  lb_grad_yy_2_stencil_update_stream$mem_2$raddr_mux_out;
uint16_t  lb_grad_yy_2_stencil_update_stream$mem_1$zero_const_out;
uint8_t  lb_grad_yy_2_stencil_update_stream_wen_out;
uint16_t  lb_grad_yy_2_stencil_update_stream$mem_2$waddr$enMux_out;
uint16_t  lb_grad_yy_2_stencil_update_stream$mem_2$raddr$enMux_out;
uint16_t  lb_grad_yy_2_stencil_update_stream$mem_1$max_const_out;
uint16_t  lb_grad_yy_2_stencil_update_stream$mem_1$c1_out;
uint16_t  lb_grad_yy_2_stencil_update_stream$mem_1$add_w_out;
uint8_t  lb_grad_yy_2_stencil_update_stream$mem_1$waddr_eq_out;
uint16_t  lb_grad_yy_2_stencil_update_stream$mem_1$waddr_mux_out;
uint16_t  lb_grad_yy_2_stencil_update_stream$mem_1$waddr$enMux_out;
uint8_t  lb_grad_yy_2_stencil_update_stream$mem_1$veq_out;
uint16_t  lb_grad_yy_2_stencil_update_stream$mem_1$add_r_out;
uint8_t  lb_grad_yy_2_stencil_update_stream$mem_1$raddr_eq_out;
uint16_t  lb_grad_yy_2_stencil_update_stream$mem_1$raddr_mux_out;
uint16_t  lb_grad_yy_2_stencil_update_stream$mem_1$raddr$enMux_out;
uint16_t  lb_grad_xy_2_stencil_update_stream$mem_2$zero_const_out;
uint16_t  lb_grad_xy_2_stencil_update_stream$mem_2$max_const_out;
uint16_t  lb_grad_xy_2_stencil_update_stream$mem_2$c1_out;
uint16_t  lb_grad_xy_2_stencil_update_stream$mem_2$add_w_out;
uint8_t  lb_grad_xy_2_stencil_update_stream$mem_2$waddr_eq_out;
uint16_t  lb_grad_xy_2_stencil_update_stream$mem_2$waddr_mux_out;
uint8_t  lb_grad_xy_2_stencil_update_stream$mem_2$veq_out;
uint16_t  lb_grad_xy_2_stencil_update_stream$mem_2$add_r_out;
uint8_t  lb_grad_xy_2_stencil_update_stream$mem_2$raddr_eq_out;
uint16_t  lb_grad_xy_2_stencil_update_stream$mem_2$raddr_mux_out;
uint16_t  lb_grad_xy_2_stencil_update_stream$mem_1$zero_const_out;
uint8_t  lb_grad_xy_2_stencil_update_stream_wen_out;
uint16_t  lb_grad_xy_2_stencil_update_stream$mem_2$waddr$enMux_out;
uint16_t  lb_grad_xy_2_stencil_update_stream$mem_2$raddr$enMux_out;
uint16_t  lb_grad_xy_2_stencil_update_stream$mem_1$max_const_out;
uint16_t  lb_grad_xy_2_stencil_update_stream$mem_1$c1_out;
uint16_t  lb_grad_xy_2_stencil_update_stream$mem_1$add_w_out;
uint8_t  lb_grad_xy_2_stencil_update_stream$mem_1$waddr_eq_out;
uint16_t  lb_grad_xy_2_stencil_update_stream$mem_1$waddr_mux_out;
uint16_t  lb_grad_xy_2_stencil_update_stream$mem_1$waddr$enMux_out;
uint8_t  lb_grad_xy_2_stencil_update_stream$mem_1$veq_out;
uint16_t  lb_grad_xy_2_stencil_update_stream$mem_1$add_r_out;
uint8_t  lb_grad_xy_2_stencil_update_stream$mem_1$raddr_eq_out;
uint16_t  lb_grad_xy_2_stencil_update_stream$mem_1$raddr_mux_out;
uint16_t  lb_grad_xy_2_stencil_update_stream$mem_1$raddr$enMux_out;
uint16_t  lb_grad_xx_2_stencil_update_stream$mem_2$zero_const_out;
uint16_t  lb_grad_xx_2_stencil_update_stream$mem_2$max_const_out;
uint16_t  lb_grad_xx_2_stencil_update_stream$mem_2$c1_out;
uint16_t  lb_grad_xx_2_stencil_update_stream$mem_2$add_w_out;
uint8_t  lb_grad_xx_2_stencil_update_stream$mem_2$waddr_eq_out;
uint16_t  lb_grad_xx_2_stencil_update_stream$mem_2$waddr_mux_out;
uint8_t  lb_grad_xx_2_stencil_update_stream$mem_2$veq_out;
uint16_t  lb_grad_xx_2_stencil_update_stream$mem_2$add_r_out;
uint8_t  lb_grad_xx_2_stencil_update_stream$mem_2$raddr_eq_out;
uint16_t  lb_grad_xx_2_stencil_update_stream$mem_2$raddr_mux_out;
uint16_t  lb_grad_xx_2_stencil_update_stream$mem_1$zero_const_out;
uint8_t  lb_grad_xx_2_stencil_update_stream_wen_out;
uint16_t  lb_grad_xx_2_stencil_update_stream$mem_2$waddr$enMux_out;
uint16_t  lb_grad_xx_2_stencil_update_stream$mem_2$raddr$enMux_out;
uint16_t  lb_padded_2_stencil_update_stream$reg_2_2_out;
uint16_t  lb_padded_2_stencil_update_stream$reg_2_1_out;
uint16_t  lb_padded_2_stencil_update_stream$reg_1_2_out;
uint16_t  lb_padded_2_stencil_update_stream$reg_1_1_out;
uint16_t  lb_padded_2_stencil_update_stream$reg_0_2_out;
uint16_t  lb_padded_2_stencil_update_stream$mem_2$waddr$reg0_out;
uint16_t  lb_padded_2_stencil_update_stream$mem_2$raddr$reg0_out;
uint16_t  lb_padded_2_stencil_update_stream$mem_2$mem_rdata;
uint16_t  lb_padded_2_stencil_update_stream$mem_1$waddr$reg0_out;
uint16_t  lb_padded_2_stencil_update_stream$mem_1$raddr$reg0_out;
uint16_t  lb_p3_cim_stencil_update_stream$reg_2_2_out;
uint16_t  lb_p3_cim_stencil_update_stream$reg_2_1_out;
uint16_t  lb_p3_cim_stencil_update_stream$reg_1_2_out;
uint16_t  lb_p3_cim_stencil_update_stream$reg_1_1_out;
uint16_t  lb_p3_cim_stencil_update_stream$reg_0_2_out;
uint16_t  lb_p3_cim_stencil_update_stream$mem_2$waddr$reg0_out;
uint16_t  lb_p3_cim_stencil_update_stream$mem_2$raddr$reg0_out;
uint16_t  lb_p3_cim_stencil_update_stream$mem_2$mem_rdata;
uint16_t  lb_p3_cim_stencil_update_stream$mem_1$waddr$reg0_out;
uint16_t  lb_p3_cim_stencil_update_stream$mem_1$raddr$reg0_out;
uint16_t  lb_grad_yy_2_stencil_update_stream$mem_2$waddr$reg0_out;
uint16_t  lb_grad_yy_2_stencil_update_stream$mem_2$raddr$reg0_out;
uint16_t  lb_grad_yy_2_stencil_update_stream$mem_2$mem_rdata;
uint16_t  lb_grad_yy_2_stencil_update_stream$mem_1$waddr$reg0_out;
uint16_t  lb_grad_yy_2_stencil_update_stream$mem_1$raddr$reg0_out;
uint16_t  lb_grad_xy_2_stencil_update_stream$mem_2$waddr$reg0_out;
uint16_t  lb_grad_xy_2_stencil_update_stream$mem_2$raddr$reg0_out;
uint16_t  lb_grad_xy_2_stencil_update_stream$mem_2$mem_rdata;
uint16_t  lb_grad_xy_2_stencil_update_stream$mem_1$waddr$reg0_out;
uint16_t  lb_grad_xy_2_stencil_update_stream$mem_1$raddr$reg0_out;
uint16_t  lb_grad_xx_2_stencil_update_stream$mem_2$waddr$reg0_out;
uint16_t  lb_grad_xx_2_stencil_update_stream$mem_2$raddr$reg0_out;
uint16_t  lb_grad_xx_2_stencil_update_stream$mem_1$max_const_out;
uint16_t  lb_grad_xx_2_stencil_update_stream$mem_1$c1_out;
uint16_t  lb_grad_xx_2_stencil_update_stream$mem_1$add_w_out;
uint8_t  lb_grad_xx_2_stencil_update_stream$mem_1$waddr_eq_out;
uint16_t  lb_grad_xx_2_stencil_update_stream$mem_1$waddr_mux_out;
uint16_t  lb_grad_xx_2_stencil_update_stream$mem_1$waddr$enMux_out;
uint16_t  lb_grad_xx_2_stencil_update_stream$mem_1$waddr$reg0_out;
uint8_t  lb_grad_xx_2_stencil_update_stream$mem_1$veq_out;
uint16_t  lb_grad_xx_2_stencil_update_stream$mem_2$mem_rdata;
uint16_t  lb_grad_xx_2_stencil_update_stream$mem_1$add_r_out;
uint8_t  lb_grad_xx_2_stencil_update_stream$mem_1$raddr_eq_out;
uint16_t  lb_grad_xx_2_stencil_update_stream$mem_1$raddr_mux_out;
uint16_t  lb_grad_xx_2_stencil_update_stream$mem_1$raddr$enMux_out;
uint16_t  lb_grad_xx_2_stencil_update_stream$mem_1$raddr$reg0_out;
uint16_t  const2__677$1_out;
uint16_t  mul_681_677_682_out;
uint16_t  const2__677_out;
uint16_t  mul_676_677_678_out;
uint16_t  add_674_678_679_out;
uint16_t  sub_679_682_683_out;
uint16_t  const2__635$1_out;
uint16_t  mul_639_635_640_out;
uint16_t  const2__635_out;
uint16_t  mul_634_635_636_out;
uint16_t  sub_632_636_637_out;
uint16_t  add_637_640_641_out;
uint16_t  sub_641_643_644_out;
uint16_t  const255__770_out;
uint16_t  const100_100_out;
uint8_t  ule100_751_768_out;
uint16_t  const0__771$1_out;
uint16_t  const4__748_out;
uint16_t  const7__739$2_out;
uint16_t  const7__739$1_out;
uint16_t  const7__739_out;
uint16_t  lb_grad_yy_2_stencil_update_stream$reg_0_2_out;
uint16_t  lb_grad_yy_2_stencil_update_stream$reg_1_1_out;
uint16_t  lb_grad_yy_2_stencil_update_stream$reg_1_2_out;
uint16_t  lb_grad_yy_2_stencil_update_stream$reg_2_2_out;
uint16_t  lb_grad_yy_2_stencil_update_stream$reg_2_1_out;
uint16_t  const0_0$2_out;
uint16_t  lb_grad_xy_2_stencil_update_stream$reg_0_2_out;
uint16_t  lb_grad_xy_2_stencil_update_stream$reg_1_1_out;
uint16_t  lb_grad_xy_2_stencil_update_stream$reg_1_2_out;
uint16_t  lb_grad_xy_2_stencil_update_stream$reg_2_2_out;
uint16_t  lb_grad_xy_2_stencil_update_stream$reg_2_1_out;
uint16_t  const0_0$1_out;
uint16_t  lb_grad_xx_2_stencil_update_stream$reg_0_2_out;
uint16_t  lb_grad_xx_2_stencil_update_stream$reg_1_1_out;
uint16_t  lb_grad_xx_2_stencil_update_stream$reg_1_2_out;
uint16_t  lb_grad_xx_2_stencil_update_stream$reg_2_2_out;
uint16_t  lb_grad_xx_2_stencil_update_stream$reg_2_1_out;
uint16_t  const0_0_out;
uint16_t  lb_padded_2_stencil_update_stream$reg_0_1_out;
uint16_t  lb_padded_2_stencil_update_stream$mem_1$mem_rdata;
uint16_t  add_683_685_686_out;
uint16_t  sub_686_688_689_out;
uint16_t  mul_715_715_716_out;
uint16_t  lb_grad_yy_2_stencil_update_stream$reg_0_1_out;
uint16_t  lb_grad_yy_2_stencil_update_stream$mem_1$mem_rdata;
uint16_t  add_717_718_719_out;
uint16_t  add_717_720_721_out;
uint16_t  add_717_722_723_out;
uint16_t  add_717_724_725_out;
uint16_t  add_717_726_727_out;
uint16_t  add_717_728_729_out;
uint16_t  add_717_730_731_out;
uint16_t  add_717_732_733_out;
uint16_t  add_717_734_735_out;
uint16_t  ashr_737_739_741_out;
uint16_t  add_644_646_647_out;
uint16_t  mul_691_693_694_out;
uint16_t  lb_grad_xy_2_stencil_update_stream$reg_0_1_out;
uint16_t  lb_grad_xy_2_stencil_update_stream$mem_1$mem_rdata;
uint16_t  add_695_696_697_out;
uint16_t  add_695_698_699_out;
uint16_t  add_695_700_701_out;
uint16_t  add_695_702_703_out;
uint16_t  add_695_704_705_out;
uint16_t  add_695_706_707_out;
uint16_t  add_695_708_709_out;
uint16_t  add_695_710_711_out;
uint16_t  add_695_712_713_out;
uint16_t  ashr_738_739_744_out;
uint16_t  mul_744_744_745_out;
uint16_t  mul_649_649_650_out;
uint16_t  lb_grad_xx_2_stencil_update_stream$reg_0_1_out;
uint16_t  lb_grad_xx_2_stencil_update_stream$mem_1$mem_rdata;
uint16_t  add_651_652_653_out;
uint16_t  add_651_654_655_out;
uint16_t  add_651_656_657_out;
uint16_t  add_651_658_659_out;
uint16_t  add_651_660_661_out;
uint16_t  add_651_662_663_out;
uint16_t  add_651_664_665_out;
uint16_t  add_651_666_667_out;
uint16_t  add_651_668_669_out;
uint16_t  ashr_736_739_740_out;
uint16_t  mul_740_741_743_out;
uint16_t  sub_743_745_746_out;
uint16_t  add_740_741_742_out;
uint16_t  mul_742_742_747_out;
uint16_t  ashr_747_748_749_out;
uint16_t  sub_746_749_750_out;
uint8_t  smax_752_753_754$scomp_out;
uint16_t  smax_752_753_754$max_mux_out;
uint8_t  smax_754_755_756$scomp_out;
uint16_t  smax_754_755_756$max_mux_out;
uint8_t  smax_756_757_758$scomp_out;
uint16_t  smax_756_757_758$max_mux_out;
uint8_t  smax_758_759_760$scomp_out;
uint16_t  smax_758_759_760$max_mux_out;
uint8_t  smax_760_761_762$scomp_out;
uint16_t  smax_760_761_762$max_mux_out;
uint8_t  smax_762_763_764$scomp_out;
uint16_t  smax_762_763_764$max_mux_out;
uint8_t  smax_764_765_766$scomp_out;
uint16_t  smax_764_765_766$max_mux_out;
uint8_t  ult_766_751_767_out;
uint8_t  bitand_767_768_769_out;
uint16_t  mux_769_770_771_out;
uint16_t  lb_p3_cim_stencil_update_stream$reg_0_1_out;
uint16_t  lb_p3_cim_stencil_update_stream$mem_1$mem_rdata;

// Simulation code

 if  (((state->self_clk_last) == 0) && ((state->self_clk) == 1)) {
// ----- Update outputs of sequential elements
lb_padded_2_stencil_update_stream$reg_2_2_out = (state->lb_padded_2_stencil_update_stream$reg_2_2);
lb_padded_2_stencil_update_stream$reg_1_2_out = (state->lb_padded_2_stencil_update_stream$reg_1_2);
lb_padded_2_stencil_update_stream$reg_0_2_out = (state->lb_padded_2_stencil_update_stream$reg_0_2);
lb_padded_2_stencil_update_stream$reg_0_1_out = (state->lb_padded_2_stencil_update_stream$reg_0_1);
lb_padded_2_stencil_update_stream$reg_2_1_out = (state->lb_padded_2_stencil_update_stream$reg_2_1);
lb_padded_2_stencil_update_stream$mem_2$waddr$reg0_out = (state->lb_padded_2_stencil_update_stream$mem_2$waddr$reg0);
lb_padded_2_stencil_update_stream$mem_2$raddr$reg0_out = (state->lb_padded_2_stencil_update_stream$mem_2$raddr$reg0);
lb_padded_2_stencil_update_stream$mem_2$mem_rdata = ((state->lb_padded_2_stencil_update_stream$mem_2$mem)[ (state->lb_padded_2_stencil_update_stream$mem_2$raddr$reg0) ]);
lb_padded_2_stencil_update_stream$reg_1_1_out = (state->lb_padded_2_stencil_update_stream$reg_1_1);
lb_padded_2_stencil_update_stream$mem_1$waddr$reg0_out = (state->lb_padded_2_stencil_update_stream$mem_1$waddr$reg0);
lb_padded_2_stencil_update_stream$mem_1$raddr$reg0_out = (state->lb_padded_2_stencil_update_stream$mem_1$raddr$reg0);
lb_padded_2_stencil_update_stream$mem_1$mem_rdata = ((state->lb_padded_2_stencil_update_stream$mem_1$mem)[ (state->lb_padded_2_stencil_update_stream$mem_1$raddr$reg0) ]);
lb_p3_cim_stencil_update_stream$reg_2_2_out = (state->lb_p3_cim_stencil_update_stream$reg_2_2);
lb_p3_cim_stencil_update_stream$reg_1_2_out = (state->lb_p3_cim_stencil_update_stream$reg_1_2);
lb_p3_cim_stencil_update_stream$reg_0_2_out = (state->lb_p3_cim_stencil_update_stream$reg_0_2);
lb_p3_cim_stencil_update_stream$reg_0_1_out = (state->lb_p3_cim_stencil_update_stream$reg_0_1);
lb_p3_cim_stencil_update_stream$reg_2_1_out = (state->lb_p3_cim_stencil_update_stream$reg_2_1);
lb_p3_cim_stencil_update_stream$mem_2$waddr$reg0_out = (state->lb_p3_cim_stencil_update_stream$mem_2$waddr$reg0);
lb_p3_cim_stencil_update_stream$mem_2$raddr$reg0_out = (state->lb_p3_cim_stencil_update_stream$mem_2$raddr$reg0);
lb_p3_cim_stencil_update_stream$mem_2$mem_rdata = ((state->lb_p3_cim_stencil_update_stream$mem_2$mem)[ (state->lb_p3_cim_stencil_update_stream$mem_2$raddr$reg0) ]);
lb_p3_cim_stencil_update_stream$reg_1_1_out = (state->lb_p3_cim_stencil_update_stream$reg_1_1);
lb_p3_cim_stencil_update_stream$mem_1$waddr$reg0_out = (state->lb_p3_cim_stencil_update_stream$mem_1$waddr$reg0);
lb_p3_cim_stencil_update_stream$mem_1$raddr$reg0_out = (state->lb_p3_cim_stencil_update_stream$mem_1$raddr$reg0);
lb_p3_cim_stencil_update_stream$mem_1$mem_rdata = ((state->lb_p3_cim_stencil_update_stream$mem_1$mem)[ (state->lb_p3_cim_stencil_update_stream$mem_1$raddr$reg0) ]);
lb_grad_yy_2_stencil_update_stream$reg_2_2_out = (state->lb_grad_yy_2_stencil_update_stream$reg_2_2);
lb_grad_yy_2_stencil_update_stream$mem_2$waddr$reg0_out = (state->lb_grad_yy_2_stencil_update_stream$mem_2$waddr$reg0);
lb_grad_yy_2_stencil_update_stream$mem_2$raddr$reg0_out = (state->lb_grad_yy_2_stencil_update_stream$mem_2$raddr$reg0);
lb_grad_yy_2_stencil_update_stream$mem_2$mem_rdata = ((state->lb_grad_yy_2_stencil_update_stream$mem_2$mem)[ (state->lb_grad_yy_2_stencil_update_stream$mem_2$raddr$reg0) ]);
lb_grad_yy_2_stencil_update_stream$mem_1$waddr$reg0_out = (state->lb_grad_yy_2_stencil_update_stream$mem_1$waddr$reg0);
lb_grad_yy_2_stencil_update_stream$mem_1$raddr$reg0_out = (state->lb_grad_yy_2_stencil_update_stream$mem_1$raddr$reg0);
lb_grad_yy_2_stencil_update_stream$mem_1$mem_rdata = ((state->lb_grad_yy_2_stencil_update_stream$mem_1$mem)[ (state->lb_grad_yy_2_stencil_update_stream$mem_1$raddr$reg0) ]);
lb_grad_xy_2_stencil_update_stream$reg_2_2_out = (state->lb_grad_xy_2_stencil_update_stream$reg_2_2);
lb_grad_xy_2_stencil_update_stream$mem_2$waddr$reg0_out = (state->lb_grad_xy_2_stencil_update_stream$mem_2$waddr$reg0);
lb_grad_xy_2_stencil_update_stream$mem_2$raddr$reg0_out = (state->lb_grad_xy_2_stencil_update_stream$mem_2$raddr$reg0);
lb_grad_xy_2_stencil_update_stream$mem_2$mem_rdata = ((state->lb_grad_xy_2_stencil_update_stream$mem_2$mem)[ (state->lb_grad_xy_2_stencil_update_stream$mem_2$raddr$reg0) ]);
lb_grad_xy_2_stencil_update_stream$mem_1$waddr$reg0_out = (state->lb_grad_xy_2_stencil_update_stream$mem_1$waddr$reg0);
lb_grad_xy_2_stencil_update_stream$mem_1$raddr$reg0_out = (state->lb_grad_xy_2_stencil_update_stream$mem_1$raddr$reg0);
lb_grad_xy_2_stencil_update_stream$mem_1$mem_rdata = ((state->lb_grad_xy_2_stencil_update_stream$mem_1$mem)[ (state->lb_grad_xy_2_stencil_update_stream$mem_1$raddr$reg0) ]);
lb_grad_xx_2_stencil_update_stream$reg_2_2_out = (state->lb_grad_xx_2_stencil_update_stream$reg_2_2);
lb_grad_xx_2_stencil_update_stream$mem_2$waddr$reg0_out = (state->lb_grad_xx_2_stencil_update_stream$mem_2$waddr$reg0);
lb_grad_xx_2_stencil_update_stream$mem_2$raddr$reg0_out = (state->lb_grad_xx_2_stencil_update_stream$mem_2$raddr$reg0);
lb_grad_xx_2_stencil_update_stream$mem_2$mem_rdata = ((state->lb_grad_xx_2_stencil_update_stream$mem_2$mem)[ (state->lb_grad_xx_2_stencil_update_stream$mem_2$raddr$reg0) ]);
lb_grad_xx_2_stencil_update_stream$mem_1$waddr$reg0_out = (state->lb_grad_xx_2_stencil_update_stream$mem_1$waddr$reg0);
lb_grad_xx_2_stencil_update_stream$mem_1$raddr$reg0_out = (state->lb_grad_xx_2_stencil_update_stream$mem_1$raddr$reg0);
lb_grad_xx_2_stencil_update_stream$mem_1$mem_rdata = ((state->lb_grad_xx_2_stencil_update_stream$mem_1$mem)[ (state->lb_grad_xx_2_stencil_update_stream$mem_1$raddr$reg0) ]);
lb_grad_yy_2_stencil_update_stream$reg_0_1_out = (state->lb_grad_yy_2_stencil_update_stream$reg_0_1);
lb_grad_yy_2_stencil_update_stream$reg_0_2_out = (state->lb_grad_yy_2_stencil_update_stream$reg_0_2);
lb_grad_yy_2_stencil_update_stream$reg_1_1_out = (state->lb_grad_yy_2_stencil_update_stream$reg_1_1);
lb_grad_yy_2_stencil_update_stream$reg_1_2_out = (state->lb_grad_yy_2_stencil_update_stream$reg_1_2);
lb_grad_yy_2_stencil_update_stream$reg_2_1_out = (state->lb_grad_yy_2_stencil_update_stream$reg_2_1);
lb_grad_xy_2_stencil_update_stream$reg_0_1_out = (state->lb_grad_xy_2_stencil_update_stream$reg_0_1);
lb_grad_xy_2_stencil_update_stream$reg_0_2_out = (state->lb_grad_xy_2_stencil_update_stream$reg_0_2);
lb_grad_xy_2_stencil_update_stream$reg_1_1_out = (state->lb_grad_xy_2_stencil_update_stream$reg_1_1);
lb_grad_xy_2_stencil_update_stream$reg_1_2_out = (state->lb_grad_xy_2_stencil_update_stream$reg_1_2);
lb_grad_xy_2_stencil_update_stream$reg_2_1_out = (state->lb_grad_xy_2_stencil_update_stream$reg_2_1);
lb_grad_xx_2_stencil_update_stream$reg_0_1_out = (state->lb_grad_xx_2_stencil_update_stream$reg_0_1);
lb_grad_xx_2_stencil_update_stream$reg_0_2_out = (state->lb_grad_xx_2_stencil_update_stream$reg_0_2);
lb_grad_xx_2_stencil_update_stream$reg_1_1_out = (state->lb_grad_xx_2_stencil_update_stream$reg_1_1);
lb_grad_xx_2_stencil_update_stream$reg_1_2_out = (state->lb_grad_xx_2_stencil_update_stream$reg_1_2);
lb_grad_xx_2_stencil_update_stream$reg_2_1_out = (state->lb_grad_xx_2_stencil_update_stream$reg_2_1);

// ----- Update combinational logic
lb_padded_2_stencil_update_stream$mem_2$zero_const_out = 0b000000000;
lb_padded_2_stencil_update_stream$mem_2$max_const_out = 0b111100110;
lb_padded_2_stencil_update_stream$mem_2$c1_out = 0b000000001;
lb_padded_2_stencil_update_stream$mem_2$add_w_out = MASK( 9, ((state->lb_padded_2_stencil_update_stream$mem_2$waddr$reg0) + /* LOCAL */lb_padded_2_stencil_update_stream$mem_2$c1_out) );
lb_padded_2_stencil_update_stream$mem_2$add_r_out = MASK( 9, ((state->lb_padded_2_stencil_update_stream$mem_2$raddr$reg0) + /* LOCAL */lb_padded_2_stencil_update_stream$mem_2$c1_out) );
lb_padded_2_stencil_update_stream$mem_1$zero_const_out = 0b000000000;
lb_padded_2_stencil_update_stream_wen_out = 1;
lb_padded_2_stencil_update_stream$mem_1$max_const_out = 0b111100110;
lb_padded_2_stencil_update_stream$mem_1$c1_out = 0b000000001;
lb_padded_2_stencil_update_stream$mem_1$add_w_out = MASK( 9, ((state->lb_padded_2_stencil_update_stream$mem_1$waddr$reg0) + /* LOCAL */lb_padded_2_stencil_update_stream$mem_1$c1_out) );
lb_padded_2_stencil_update_stream$mem_1$add_r_out = MASK( 9, ((state->lb_padded_2_stencil_update_stream$mem_1$raddr$reg0) + /* LOCAL */lb_padded_2_stencil_update_stream$mem_1$c1_out) );
lb_p3_cim_stencil_update_stream$mem_2$zero_const_out = 0b000000000;
lb_p3_cim_stencil_update_stream$mem_2$max_const_out = 0b111100010;
lb_p3_cim_stencil_update_stream$mem_2$c1_out = 0b000000001;
lb_p3_cim_stencil_update_stream$mem_2$add_w_out = MASK( 9, ((state->lb_p3_cim_stencil_update_stream$mem_2$waddr$reg0) + /* LOCAL */lb_p3_cim_stencil_update_stream$mem_2$c1_out) );
lb_p3_cim_stencil_update_stream$mem_2$add_r_out = MASK( 9, ((state->lb_p3_cim_stencil_update_stream$mem_2$raddr$reg0) + /* LOCAL */lb_p3_cim_stencil_update_stream$mem_2$c1_out) );
lb_p3_cim_stencil_update_stream$mem_1$zero_const_out = 0b000000000;
lb_p3_cim_stencil_update_stream_wen_out = 1;
lb_p3_cim_stencil_update_stream$mem_1$max_const_out = 0b111100010;
lb_p3_cim_stencil_update_stream$mem_1$c1_out = 0b000000001;
lb_p3_cim_stencil_update_stream$mem_1$add_w_out = MASK( 9, ((state->lb_p3_cim_stencil_update_stream$mem_1$waddr$reg0) + /* LOCAL */lb_p3_cim_stencil_update_stream$mem_1$c1_out) );
lb_p3_cim_stencil_update_stream$mem_1$add_r_out = MASK( 9, ((state->lb_p3_cim_stencil_update_stream$mem_1$raddr$reg0) + /* LOCAL */lb_p3_cim_stencil_update_stream$mem_1$c1_out) );
lb_grad_yy_2_stencil_update_stream$mem_2$zero_const_out = 0b000000000;
lb_grad_yy_2_stencil_update_stream$mem_2$max_const_out = 0b111100100;
lb_grad_yy_2_stencil_update_stream$mem_2$c1_out = 0b000000001;
lb_grad_yy_2_stencil_update_stream$mem_2$add_w_out = MASK( 9, ((state->lb_grad_yy_2_stencil_update_stream$mem_2$waddr$reg0) + /* LOCAL */lb_grad_yy_2_stencil_update_stream$mem_2$c1_out) );
lb_grad_yy_2_stencil_update_stream$mem_2$add_r_out = MASK( 9, ((state->lb_grad_yy_2_stencil_update_stream$mem_2$raddr$reg0) + /* LOCAL */lb_grad_yy_2_stencil_update_stream$mem_2$c1_out) );
lb_grad_yy_2_stencil_update_stream$mem_1$zero_const_out = 0b000000000;
lb_grad_yy_2_stencil_update_stream_wen_out = 1;
lb_grad_yy_2_stencil_update_stream$mem_1$max_const_out = 0b111100100;
lb_grad_yy_2_stencil_update_stream$mem_1$c1_out = 0b000000001;
lb_grad_yy_2_stencil_update_stream$mem_1$add_w_out = MASK( 9, ((state->lb_grad_yy_2_stencil_update_stream$mem_1$waddr$reg0) + /* LOCAL */lb_grad_yy_2_stencil_update_stream$mem_1$c1_out) );
lb_grad_yy_2_stencil_update_stream$mem_1$add_r_out = MASK( 9, ((state->lb_grad_yy_2_stencil_update_stream$mem_1$raddr$reg0) + /* LOCAL */lb_grad_yy_2_stencil_update_stream$mem_1$c1_out) );
lb_grad_xy_2_stencil_update_stream$mem_2$zero_const_out = 0b000000000;
lb_grad_xy_2_stencil_update_stream$mem_2$max_const_out = 0b111100100;
lb_grad_xy_2_stencil_update_stream$mem_2$c1_out = 0b000000001;
lb_grad_xy_2_stencil_update_stream$mem_2$add_w_out = MASK( 9, ((state->lb_grad_xy_2_stencil_update_stream$mem_2$waddr$reg0) + /* LOCAL */lb_grad_xy_2_stencil_update_stream$mem_2$c1_out) );
lb_grad_xy_2_stencil_update_stream$mem_2$add_r_out = MASK( 9, ((state->lb_grad_xy_2_stencil_update_stream$mem_2$raddr$reg0) + /* LOCAL */lb_grad_xy_2_stencil_update_stream$mem_2$c1_out) );
lb_grad_xy_2_stencil_update_stream$mem_1$zero_const_out = 0b000000000;
lb_grad_xy_2_stencil_update_stream_wen_out = 1;
lb_grad_xy_2_stencil_update_stream$mem_1$max_const_out = 0b111100100;
lb_grad_xy_2_stencil_update_stream$mem_1$c1_out = 0b000000001;
lb_grad_xy_2_stencil_update_stream$mem_1$add_w_out = MASK( 9, ((state->lb_grad_xy_2_stencil_update_stream$mem_1$waddr$reg0) + /* LOCAL */lb_grad_xy_2_stencil_update_stream$mem_1$c1_out) );
lb_grad_xy_2_stencil_update_stream$mem_1$add_r_out = MASK( 9, ((state->lb_grad_xy_2_stencil_update_stream$mem_1$raddr$reg0) + /* LOCAL */lb_grad_xy_2_stencil_update_stream$mem_1$c1_out) );
lb_grad_xx_2_stencil_update_stream$mem_2$zero_const_out = 0b000000000;
lb_grad_xx_2_stencil_update_stream$mem_2$max_const_out = 0b111100100;
lb_grad_xx_2_stencil_update_stream$mem_2$c1_out = 0b000000001;
lb_grad_xx_2_stencil_update_stream$mem_2$add_w_out = MASK( 9, ((state->lb_grad_xx_2_stencil_update_stream$mem_2$waddr$reg0) + /* LOCAL */lb_grad_xx_2_stencil_update_stream$mem_2$c1_out) );
lb_grad_xx_2_stencil_update_stream$mem_2$add_r_out = MASK( 9, ((state->lb_grad_xx_2_stencil_update_stream$mem_2$raddr$reg0) + /* LOCAL */lb_grad_xx_2_stencil_update_stream$mem_2$c1_out) );
lb_grad_xx_2_stencil_update_stream$mem_1$zero_const_out = 0b000000000;
lb_grad_xx_2_stencil_update_stream_wen_out = 1;
lb_grad_xx_2_stencil_update_stream$mem_1$max_const_out = 0b111100100;
lb_grad_xx_2_stencil_update_stream$mem_1$c1_out = 0b000000001;
lb_grad_xx_2_stencil_update_stream$mem_1$add_w_out = MASK( 9, ((state->lb_grad_xx_2_stencil_update_stream$mem_1$waddr$reg0) + /* LOCAL */lb_grad_xx_2_stencil_update_stream$mem_1$c1_out) );
lb_grad_xx_2_stencil_update_stream$mem_1$add_r_out = MASK( 9, ((state->lb_grad_xx_2_stencil_update_stream$mem_1$raddr$reg0) + /* LOCAL */lb_grad_xx_2_stencil_update_stream$mem_1$c1_out) );
sub_686_688_689_out = ((((((state->lb_padded_2_stencil_update_stream$reg_0_2) - (state->lb_padded_2_stencil_update_stream$reg_2_2)) + ((state->lb_padded_2_stencil_update_stream$reg_0_1) * 0b0000000000000010)) - ((state->lb_padded_2_stencil_update_stream$reg_2_1) * 0b0000000000000010)) + (state->self_in_0)) - lb_padded_2_stencil_update_stream$mem_2$mem_rdata);
mul_715_715_716_out = (/* LOCAL */sub_686_688_689_out * /* LOCAL */sub_686_688_689_out);
ashr_737_739_741_out = ((((((((((0b0000000000000000 + /* LOCAL */mul_715_715_716_out) + (state->lb_grad_yy_2_stencil_update_stream$reg_2_1)) + lb_grad_yy_2_stencil_update_stream$mem_2$mem_rdata) + (state->lb_grad_yy_2_stencil_update_stream$reg_1_2)) + (state->lb_grad_yy_2_stencil_update_stream$reg_1_1)) + lb_grad_yy_2_stencil_update_stream$mem_1$mem_rdata) + (state->lb_grad_yy_2_stencil_update_stream$reg_0_2)) + (state->lb_grad_yy_2_stencil_update_stream$reg_0_1)) + /* LOCAL */mul_715_715_716_out) >> 0b0000000000000111);
add_644_646_647_out = (((((lb_padded_2_stencil_update_stream$mem_2$mem_rdata - (state->lb_padded_2_stencil_update_stream$reg_2_2)) - ((state->lb_padded_2_stencil_update_stream$reg_1_2) * 0b0000000000000010)) + (lb_padded_2_stencil_update_stream$mem_1$mem_rdata * 0b0000000000000010)) - (state->lb_padded_2_stencil_update_stream$reg_0_2)) + (state->self_in_0));
mul_691_693_694_out = (/* LOCAL */add_644_646_647_out * /* LOCAL */sub_686_688_689_out);
ashr_738_739_744_out = ((((((((((0b0000000000000000 + /* LOCAL */mul_691_693_694_out) + (state->lb_grad_xy_2_stencil_update_stream$reg_2_1)) + lb_grad_xy_2_stencil_update_stream$mem_2$mem_rdata) + (state->lb_grad_xy_2_stencil_update_stream$reg_1_2)) + (state->lb_grad_xy_2_stencil_update_stream$reg_1_1)) + lb_grad_xy_2_stencil_update_stream$mem_1$mem_rdata) + (state->lb_grad_xy_2_stencil_update_stream$reg_0_2)) + (state->lb_grad_xy_2_stencil_update_stream$reg_0_1)) + /* LOCAL */mul_691_693_694_out) >> 0b0000000000000111);
mul_649_649_650_out = (/* LOCAL */add_644_646_647_out * /* LOCAL */add_644_646_647_out);
ashr_736_739_740_out = ((((((((((0b0000000000000000 + /* LOCAL */mul_649_649_650_out) + (state->lb_grad_xx_2_stencil_update_stream$reg_2_1)) + lb_grad_xx_2_stencil_update_stream$mem_2$mem_rdata) + (state->lb_grad_xx_2_stencil_update_stream$reg_1_2)) + (state->lb_grad_xx_2_stencil_update_stream$reg_1_1)) + lb_grad_xx_2_stencil_update_stream$mem_1$mem_rdata) + (state->lb_grad_xx_2_stencil_update_stream$reg_0_2)) + (state->lb_grad_xx_2_stencil_update_stream$reg_0_1)) + /* LOCAL */mul_649_649_650_out) >> 0b0000000000000111);
add_740_741_742_out = (/* LOCAL */ashr_736_739_740_out + /* LOCAL */ashr_737_739_741_out);
sub_746_749_750_out = (((/* LOCAL */ashr_736_739_740_out * /* LOCAL */ashr_737_739_741_out) - (/* LOCAL */ashr_738_739_744_out * /* LOCAL */ashr_738_739_744_out)) - ((/* LOCAL */add_740_741_742_out * /* LOCAL */add_740_741_742_out) >> 0b0000000000000100));
smax_752_753_754$max_mux_out = (MASK( 1, ((int16_t) (/* LOCAL */sub_746_749_750_out)) >= ((int16_t) ((state->lb_p3_cim_stencil_update_stream$reg_2_1))) ) ? /* LOCAL */sub_746_749_750_out : (state->lb_p3_cim_stencil_update_stream$reg_2_1));
smax_754_755_756$max_mux_out = (MASK( 1, ((int16_t) (/* LOCAL */smax_752_753_754$max_mux_out)) >= ((int16_t) (lb_p3_cim_stencil_update_stream$mem_2$mem_rdata)) ) ? /* LOCAL */smax_752_753_754$max_mux_out : lb_p3_cim_stencil_update_stream$mem_2$mem_rdata);
smax_756_757_758$max_mux_out = (MASK( 1, ((int16_t) (/* LOCAL */smax_754_755_756$max_mux_out)) >= ((int16_t) ((state->lb_p3_cim_stencil_update_stream$reg_1_2))) ) ? /* LOCAL */smax_754_755_756$max_mux_out : (state->lb_p3_cim_stencil_update_stream$reg_1_2));
smax_758_759_760$max_mux_out = (MASK( 1, ((int16_t) (/* LOCAL */smax_756_757_758$max_mux_out)) >= ((int16_t) (lb_p3_cim_stencil_update_stream$mem_1$mem_rdata)) ) ? /* LOCAL */smax_756_757_758$max_mux_out : lb_p3_cim_stencil_update_stream$mem_1$mem_rdata);
smax_760_761_762$max_mux_out = (MASK( 1, ((int16_t) (/* LOCAL */smax_758_759_760$max_mux_out)) >= ((int16_t) ((state->lb_p3_cim_stencil_update_stream$reg_0_2))) ) ? /* LOCAL */smax_758_759_760$max_mux_out : (state->lb_p3_cim_stencil_update_stream$reg_0_2));
smax_762_763_764$max_mux_out = (MASK( 1, ((int16_t) (/* LOCAL */smax_760_761_762$max_mux_out)) >= ((int16_t) ((state->lb_p3_cim_stencil_update_stream$reg_0_1))) ) ? /* LOCAL */smax_760_761_762$max_mux_out : (state->lb_p3_cim_stencil_update_stream$reg_0_1));
(state->self_out) = (MASK( 1, (MASK( 1, ((MASK( 1, ((int16_t) (/* LOCAL */smax_762_763_764$max_mux_out)) >= ((int16_t) (/* LOCAL */sub_746_749_750_out)) ) ? /* LOCAL */smax_762_763_764$max_mux_out : /* LOCAL */sub_746_749_750_out) < (state->lb_p3_cim_stencil_update_stream$reg_1_1)) ) & MASK( 1, (0b0000000001100100 <= (state->lb_p3_cim_stencil_update_stream$reg_1_1)) )) ) ? 0b0000000000000000 : 0b0000000011111111);

// ----- Update stored state in sequential elements
(state->lb_padded_2_stencil_update_stream$reg_2_2) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? (state->lb_padded_2_stencil_update_stream$reg_2_1) : (state->lb_padded_2_stencil_update_stream$reg_2_2));
(state->lb_padded_2_stencil_update_stream$reg_2_1) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? lb_padded_2_stencil_update_stream$mem_2$mem_rdata : (state->lb_padded_2_stencil_update_stream$reg_2_1));
(state->lb_padded_2_stencil_update_stream$reg_1_2) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? (state->lb_padded_2_stencil_update_stream$reg_1_1) : (state->lb_padded_2_stencil_update_stream$reg_1_2));
(state->lb_padded_2_stencil_update_stream$reg_1_1) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? lb_padded_2_stencil_update_stream$mem_1$mem_rdata : (state->lb_padded_2_stencil_update_stream$reg_1_1));
(state->lb_padded_2_stencil_update_stream$reg_0_2) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? (state->lb_padded_2_stencil_update_stream$reg_0_1) : (state->lb_padded_2_stencil_update_stream$reg_0_2));
(state->lb_padded_2_stencil_update_stream$mem_2$waddr$reg0) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? (/* LOCAL */lb_padded_2_stencil_update_stream_wen_out ? (MASK( 1, (/* LOCAL */lb_padded_2_stencil_update_stream$mem_2$add_w_out == /* LOCAL */lb_padded_2_stencil_update_stream$mem_2$max_const_out) ) ? /* LOCAL */lb_padded_2_stencil_update_stream$mem_2$zero_const_out : /* LOCAL */lb_padded_2_stencil_update_stream$mem_2$add_w_out) : (state->lb_padded_2_stencil_update_stream$mem_2$waddr$reg0)) : (state->lb_padded_2_stencil_update_stream$mem_2$waddr$reg0));
(state->lb_padded_2_stencil_update_stream$mem_2$raddr$reg0) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? (/* LOCAL */lb_padded_2_stencil_update_stream_wen_out ? (MASK( 1, (/* LOCAL */lb_padded_2_stencil_update_stream$mem_2$add_r_out == /* LOCAL */lb_padded_2_stencil_update_stream$mem_2$max_const_out) ) ? /* LOCAL */lb_padded_2_stencil_update_stream$mem_2$zero_const_out : /* LOCAL */lb_padded_2_stencil_update_stream$mem_2$add_r_out) : (state->lb_padded_2_stencil_update_stream$mem_2$raddr$reg0)) : (state->lb_padded_2_stencil_update_stream$mem_2$raddr$reg0));
(state->lb_padded_2_stencil_update_stream$mem_2$mem)[ (state->lb_padded_2_stencil_update_stream$mem_2$waddr$reg0) ] = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1)) && /* LOCAL */lb_padded_2_stencil_update_stream_wen_out) ? lb_padded_2_stencil_update_stream$mem_1$mem_rdata : (state->lb_padded_2_stencil_update_stream$mem_2$mem)[ (state->lb_padded_2_stencil_update_stream$mem_2$waddr$reg0) ]);
(state->lb_padded_2_stencil_update_stream$mem_1$waddr$reg0) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? (/* LOCAL */lb_padded_2_stencil_update_stream_wen_out ? (MASK( 1, (/* LOCAL */lb_padded_2_stencil_update_stream$mem_1$add_w_out == /* LOCAL */lb_padded_2_stencil_update_stream$mem_1$max_const_out) ) ? /* LOCAL */lb_padded_2_stencil_update_stream$mem_1$zero_const_out : /* LOCAL */lb_padded_2_stencil_update_stream$mem_1$add_w_out) : (state->lb_padded_2_stencil_update_stream$mem_1$waddr$reg0)) : (state->lb_padded_2_stencil_update_stream$mem_1$waddr$reg0));
(state->lb_padded_2_stencil_update_stream$mem_1$raddr$reg0) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? (/* LOCAL */lb_padded_2_stencil_update_stream_wen_out ? (MASK( 1, (/* LOCAL */lb_padded_2_stencil_update_stream$mem_1$add_r_out == /* LOCAL */lb_padded_2_stencil_update_stream$mem_1$max_const_out) ) ? /* LOCAL */lb_padded_2_stencil_update_stream$mem_1$zero_const_out : /* LOCAL */lb_padded_2_stencil_update_stream$mem_1$add_r_out) : (state->lb_padded_2_stencil_update_stream$mem_1$raddr$reg0)) : (state->lb_padded_2_stencil_update_stream$mem_1$raddr$reg0));
(state->lb_p3_cim_stencil_update_stream$reg_2_2) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? (state->lb_p3_cim_stencil_update_stream$reg_2_1) : (state->lb_p3_cim_stencil_update_stream$reg_2_2));
(state->lb_p3_cim_stencil_update_stream$reg_2_1) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? lb_p3_cim_stencil_update_stream$mem_2$mem_rdata : (state->lb_p3_cim_stencil_update_stream$reg_2_1));
(state->lb_p3_cim_stencil_update_stream$reg_1_2) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? (state->lb_p3_cim_stencil_update_stream$reg_1_1) : (state->lb_p3_cim_stencil_update_stream$reg_1_2));
(state->lb_p3_cim_stencil_update_stream$reg_1_1) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? lb_p3_cim_stencil_update_stream$mem_1$mem_rdata : (state->lb_p3_cim_stencil_update_stream$reg_1_1));
(state->lb_p3_cim_stencil_update_stream$reg_0_2) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? (state->lb_p3_cim_stencil_update_stream$reg_0_1) : (state->lb_p3_cim_stencil_update_stream$reg_0_2));
(state->lb_p3_cim_stencil_update_stream$mem_2$waddr$reg0) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? (/* LOCAL */lb_p3_cim_stencil_update_stream_wen_out ? (MASK( 1, (/* LOCAL */lb_p3_cim_stencil_update_stream$mem_2$add_w_out == /* LOCAL */lb_p3_cim_stencil_update_stream$mem_2$max_const_out) ) ? /* LOCAL */lb_p3_cim_stencil_update_stream$mem_2$zero_const_out : /* LOCAL */lb_p3_cim_stencil_update_stream$mem_2$add_w_out) : (state->lb_p3_cim_stencil_update_stream$mem_2$waddr$reg0)) : (state->lb_p3_cim_stencil_update_stream$mem_2$waddr$reg0));
(state->lb_p3_cim_stencil_update_stream$mem_2$raddr$reg0) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? (/* LOCAL */lb_p3_cim_stencil_update_stream_wen_out ? (MASK( 1, (/* LOCAL */lb_p3_cim_stencil_update_stream$mem_2$add_r_out == /* LOCAL */lb_p3_cim_stencil_update_stream$mem_2$max_const_out) ) ? /* LOCAL */lb_p3_cim_stencil_update_stream$mem_2$zero_const_out : /* LOCAL */lb_p3_cim_stencil_update_stream$mem_2$add_r_out) : (state->lb_p3_cim_stencil_update_stream$mem_2$raddr$reg0)) : (state->lb_p3_cim_stencil_update_stream$mem_2$raddr$reg0));
(state->lb_p3_cim_stencil_update_stream$mem_2$mem)[ (state->lb_p3_cim_stencil_update_stream$mem_2$waddr$reg0) ] = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1)) && /* LOCAL */lb_p3_cim_stencil_update_stream_wen_out) ? lb_p3_cim_stencil_update_stream$mem_1$mem_rdata : (state->lb_p3_cim_stencil_update_stream$mem_2$mem)[ (state->lb_p3_cim_stencil_update_stream$mem_2$waddr$reg0) ]);
(state->lb_p3_cim_stencil_update_stream$mem_1$waddr$reg0) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? (/* LOCAL */lb_p3_cim_stencil_update_stream_wen_out ? (MASK( 1, (/* LOCAL */lb_p3_cim_stencil_update_stream$mem_1$add_w_out == /* LOCAL */lb_p3_cim_stencil_update_stream$mem_1$max_const_out) ) ? /* LOCAL */lb_p3_cim_stencil_update_stream$mem_1$zero_const_out : /* LOCAL */lb_p3_cim_stencil_update_stream$mem_1$add_w_out) : (state->lb_p3_cim_stencil_update_stream$mem_1$waddr$reg0)) : (state->lb_p3_cim_stencil_update_stream$mem_1$waddr$reg0));
(state->lb_p3_cim_stencil_update_stream$mem_1$raddr$reg0) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? (/* LOCAL */lb_p3_cim_stencil_update_stream_wen_out ? (MASK( 1, (/* LOCAL */lb_p3_cim_stencil_update_stream$mem_1$add_r_out == /* LOCAL */lb_p3_cim_stencil_update_stream$mem_1$max_const_out) ) ? /* LOCAL */lb_p3_cim_stencil_update_stream$mem_1$zero_const_out : /* LOCAL */lb_p3_cim_stencil_update_stream$mem_1$add_r_out) : (state->lb_p3_cim_stencil_update_stream$mem_1$raddr$reg0)) : (state->lb_p3_cim_stencil_update_stream$mem_1$raddr$reg0));
(state->lb_grad_yy_2_stencil_update_stream$mem_2$waddr$reg0) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? (/* LOCAL */lb_grad_yy_2_stencil_update_stream_wen_out ? (MASK( 1, (/* LOCAL */lb_grad_yy_2_stencil_update_stream$mem_2$add_w_out == /* LOCAL */lb_grad_yy_2_stencil_update_stream$mem_2$max_const_out) ) ? /* LOCAL */lb_grad_yy_2_stencil_update_stream$mem_2$zero_const_out : /* LOCAL */lb_grad_yy_2_stencil_update_stream$mem_2$add_w_out) : (state->lb_grad_yy_2_stencil_update_stream$mem_2$waddr$reg0)) : (state->lb_grad_yy_2_stencil_update_stream$mem_2$waddr$reg0));
(state->lb_grad_yy_2_stencil_update_stream$mem_2$raddr$reg0) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? (/* LOCAL */lb_grad_yy_2_stencil_update_stream_wen_out ? (MASK( 1, (/* LOCAL */lb_grad_yy_2_stencil_update_stream$mem_2$add_r_out == /* LOCAL */lb_grad_yy_2_stencil_update_stream$mem_2$max_const_out) ) ? /* LOCAL */lb_grad_yy_2_stencil_update_stream$mem_2$zero_const_out : /* LOCAL */lb_grad_yy_2_stencil_update_stream$mem_2$add_r_out) : (state->lb_grad_yy_2_stencil_update_stream$mem_2$raddr$reg0)) : (state->lb_grad_yy_2_stencil_update_stream$mem_2$raddr$reg0));
(state->lb_grad_yy_2_stencil_update_stream$mem_2$mem)[ (state->lb_grad_yy_2_stencil_update_stream$mem_2$waddr$reg0) ] = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1)) && /* LOCAL */lb_grad_yy_2_stencil_update_stream_wen_out) ? lb_grad_yy_2_stencil_update_stream$mem_1$mem_rdata : (state->lb_grad_yy_2_stencil_update_stream$mem_2$mem)[ (state->lb_grad_yy_2_stencil_update_stream$mem_2$waddr$reg0) ]);
(state->lb_grad_yy_2_stencil_update_stream$mem_1$waddr$reg0) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? (/* LOCAL */lb_grad_yy_2_stencil_update_stream_wen_out ? (MASK( 1, (/* LOCAL */lb_grad_yy_2_stencil_update_stream$mem_1$add_w_out == /* LOCAL */lb_grad_yy_2_stencil_update_stream$mem_1$max_const_out) ) ? /* LOCAL */lb_grad_yy_2_stencil_update_stream$mem_1$zero_const_out : /* LOCAL */lb_grad_yy_2_stencil_update_stream$mem_1$add_w_out) : (state->lb_grad_yy_2_stencil_update_stream$mem_1$waddr$reg0)) : (state->lb_grad_yy_2_stencil_update_stream$mem_1$waddr$reg0));
(state->lb_grad_yy_2_stencil_update_stream$mem_1$raddr$reg0) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? (/* LOCAL */lb_grad_yy_2_stencil_update_stream_wen_out ? (MASK( 1, (/* LOCAL */lb_grad_yy_2_stencil_update_stream$mem_1$add_r_out == /* LOCAL */lb_grad_yy_2_stencil_update_stream$mem_1$max_const_out) ) ? /* LOCAL */lb_grad_yy_2_stencil_update_stream$mem_1$zero_const_out : /* LOCAL */lb_grad_yy_2_stencil_update_stream$mem_1$add_r_out) : (state->lb_grad_yy_2_stencil_update_stream$mem_1$raddr$reg0)) : (state->lb_grad_yy_2_stencil_update_stream$mem_1$raddr$reg0));
(state->lb_grad_xy_2_stencil_update_stream$mem_2$waddr$reg0) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? (/* LOCAL */lb_grad_xy_2_stencil_update_stream_wen_out ? (MASK( 1, (/* LOCAL */lb_grad_xy_2_stencil_update_stream$mem_2$add_w_out == /* LOCAL */lb_grad_xy_2_stencil_update_stream$mem_2$max_const_out) ) ? /* LOCAL */lb_grad_xy_2_stencil_update_stream$mem_2$zero_const_out : /* LOCAL */lb_grad_xy_2_stencil_update_stream$mem_2$add_w_out) : (state->lb_grad_xy_2_stencil_update_stream$mem_2$waddr$reg0)) : (state->lb_grad_xy_2_stencil_update_stream$mem_2$waddr$reg0));
(state->lb_grad_xy_2_stencil_update_stream$mem_2$raddr$reg0) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? (/* LOCAL */lb_grad_xy_2_stencil_update_stream_wen_out ? (MASK( 1, (/* LOCAL */lb_grad_xy_2_stencil_update_stream$mem_2$add_r_out == /* LOCAL */lb_grad_xy_2_stencil_update_stream$mem_2$max_const_out) ) ? /* LOCAL */lb_grad_xy_2_stencil_update_stream$mem_2$zero_const_out : /* LOCAL */lb_grad_xy_2_stencil_update_stream$mem_2$add_r_out) : (state->lb_grad_xy_2_stencil_update_stream$mem_2$raddr$reg0)) : (state->lb_grad_xy_2_stencil_update_stream$mem_2$raddr$reg0));
(state->lb_grad_xy_2_stencil_update_stream$mem_2$mem)[ (state->lb_grad_xy_2_stencil_update_stream$mem_2$waddr$reg0) ] = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1)) && /* LOCAL */lb_grad_xy_2_stencil_update_stream_wen_out) ? lb_grad_xy_2_stencil_update_stream$mem_1$mem_rdata : (state->lb_grad_xy_2_stencil_update_stream$mem_2$mem)[ (state->lb_grad_xy_2_stencil_update_stream$mem_2$waddr$reg0) ]);
(state->lb_grad_xy_2_stencil_update_stream$mem_1$waddr$reg0) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? (/* LOCAL */lb_grad_xy_2_stencil_update_stream_wen_out ? (MASK( 1, (/* LOCAL */lb_grad_xy_2_stencil_update_stream$mem_1$add_w_out == /* LOCAL */lb_grad_xy_2_stencil_update_stream$mem_1$max_const_out) ) ? /* LOCAL */lb_grad_xy_2_stencil_update_stream$mem_1$zero_const_out : /* LOCAL */lb_grad_xy_2_stencil_update_stream$mem_1$add_w_out) : (state->lb_grad_xy_2_stencil_update_stream$mem_1$waddr$reg0)) : (state->lb_grad_xy_2_stencil_update_stream$mem_1$waddr$reg0));
(state->lb_grad_xy_2_stencil_update_stream$mem_1$raddr$reg0) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? (/* LOCAL */lb_grad_xy_2_stencil_update_stream_wen_out ? (MASK( 1, (/* LOCAL */lb_grad_xy_2_stencil_update_stream$mem_1$add_r_out == /* LOCAL */lb_grad_xy_2_stencil_update_stream$mem_1$max_const_out) ) ? /* LOCAL */lb_grad_xy_2_stencil_update_stream$mem_1$zero_const_out : /* LOCAL */lb_grad_xy_2_stencil_update_stream$mem_1$add_r_out) : (state->lb_grad_xy_2_stencil_update_stream$mem_1$raddr$reg0)) : (state->lb_grad_xy_2_stencil_update_stream$mem_1$raddr$reg0));
(state->lb_grad_xx_2_stencil_update_stream$mem_2$waddr$reg0) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? (/* LOCAL */lb_grad_xx_2_stencil_update_stream_wen_out ? (MASK( 1, (/* LOCAL */lb_grad_xx_2_stencil_update_stream$mem_2$add_w_out == /* LOCAL */lb_grad_xx_2_stencil_update_stream$mem_2$max_const_out) ) ? /* LOCAL */lb_grad_xx_2_stencil_update_stream$mem_2$zero_const_out : /* LOCAL */lb_grad_xx_2_stencil_update_stream$mem_2$add_w_out) : (state->lb_grad_xx_2_stencil_update_stream$mem_2$waddr$reg0)) : (state->lb_grad_xx_2_stencil_update_stream$mem_2$waddr$reg0));
(state->lb_grad_xx_2_stencil_update_stream$mem_2$raddr$reg0) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? (/* LOCAL */lb_grad_xx_2_stencil_update_stream_wen_out ? (MASK( 1, (/* LOCAL */lb_grad_xx_2_stencil_update_stream$mem_2$add_r_out == /* LOCAL */lb_grad_xx_2_stencil_update_stream$mem_2$max_const_out) ) ? /* LOCAL */lb_grad_xx_2_stencil_update_stream$mem_2$zero_const_out : /* LOCAL */lb_grad_xx_2_stencil_update_stream$mem_2$add_r_out) : (state->lb_grad_xx_2_stencil_update_stream$mem_2$raddr$reg0)) : (state->lb_grad_xx_2_stencil_update_stream$mem_2$raddr$reg0));
(state->lb_grad_xx_2_stencil_update_stream$mem_1$waddr$reg0) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? (/* LOCAL */lb_grad_xx_2_stencil_update_stream_wen_out ? (MASK( 1, (/* LOCAL */lb_grad_xx_2_stencil_update_stream$mem_1$add_w_out == /* LOCAL */lb_grad_xx_2_stencil_update_stream$mem_1$max_const_out) ) ? /* LOCAL */lb_grad_xx_2_stencil_update_stream$mem_1$zero_const_out : /* LOCAL */lb_grad_xx_2_stencil_update_stream$mem_1$add_w_out) : (state->lb_grad_xx_2_stencil_update_stream$mem_1$waddr$reg0)) : (state->lb_grad_xx_2_stencil_update_stream$mem_1$waddr$reg0));
(state->lb_grad_xx_2_stencil_update_stream$mem_2$mem)[ (state->lb_grad_xx_2_stencil_update_stream$mem_2$waddr$reg0) ] = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1)) && /* LOCAL */lb_grad_xx_2_stencil_update_stream_wen_out) ? lb_grad_xx_2_stencil_update_stream$mem_1$mem_rdata : (state->lb_grad_xx_2_stencil_update_stream$mem_2$mem)[ (state->lb_grad_xx_2_stencil_update_stream$mem_2$waddr$reg0) ]);
(state->lb_grad_xx_2_stencil_update_stream$mem_1$raddr$reg0) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? (/* LOCAL */lb_grad_xx_2_stencil_update_stream_wen_out ? (MASK( 1, (/* LOCAL */lb_grad_xx_2_stencil_update_stream$mem_1$add_r_out == /* LOCAL */lb_grad_xx_2_stencil_update_stream$mem_1$max_const_out) ) ? /* LOCAL */lb_grad_xx_2_stencil_update_stream$mem_1$zero_const_out : /* LOCAL */lb_grad_xx_2_stencil_update_stream$mem_1$add_r_out) : (state->lb_grad_xx_2_stencil_update_stream$mem_1$raddr$reg0)) : (state->lb_grad_xx_2_stencil_update_stream$mem_1$raddr$reg0));
(state->lb_grad_yy_2_stencil_update_stream$reg_0_2) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? (state->lb_grad_yy_2_stencil_update_stream$reg_0_1) : (state->lb_grad_yy_2_stencil_update_stream$reg_0_2));
(state->lb_grad_yy_2_stencil_update_stream$reg_1_1) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? lb_grad_yy_2_stencil_update_stream$mem_1$mem_rdata : (state->lb_grad_yy_2_stencil_update_stream$reg_1_1));
(state->lb_grad_yy_2_stencil_update_stream$reg_1_2) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? (state->lb_grad_yy_2_stencil_update_stream$reg_1_1) : (state->lb_grad_yy_2_stencil_update_stream$reg_1_2));
(state->lb_grad_yy_2_stencil_update_stream$reg_2_2) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? (state->lb_grad_yy_2_stencil_update_stream$reg_2_1) : (state->lb_grad_yy_2_stencil_update_stream$reg_2_2));
(state->lb_grad_yy_2_stencil_update_stream$reg_2_1) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? lb_grad_yy_2_stencil_update_stream$mem_2$mem_rdata : (state->lb_grad_yy_2_stencil_update_stream$reg_2_1));
(state->lb_grad_xy_2_stencil_update_stream$reg_0_2) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? (state->lb_grad_xy_2_stencil_update_stream$reg_0_1) : (state->lb_grad_xy_2_stencil_update_stream$reg_0_2));
(state->lb_grad_xy_2_stencil_update_stream$reg_1_1) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? lb_grad_xy_2_stencil_update_stream$mem_1$mem_rdata : (state->lb_grad_xy_2_stencil_update_stream$reg_1_1));
(state->lb_grad_xy_2_stencil_update_stream$reg_1_2) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? (state->lb_grad_xy_2_stencil_update_stream$reg_1_1) : (state->lb_grad_xy_2_stencil_update_stream$reg_1_2));
(state->lb_grad_xy_2_stencil_update_stream$reg_2_2) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? (state->lb_grad_xy_2_stencil_update_stream$reg_2_1) : (state->lb_grad_xy_2_stencil_update_stream$reg_2_2));
(state->lb_grad_xy_2_stencil_update_stream$reg_2_1) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? lb_grad_xy_2_stencil_update_stream$mem_2$mem_rdata : (state->lb_grad_xy_2_stencil_update_stream$reg_2_1));
(state->lb_grad_xx_2_stencil_update_stream$reg_0_2) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? (state->lb_grad_xx_2_stencil_update_stream$reg_0_1) : (state->lb_grad_xx_2_stencil_update_stream$reg_0_2));
(state->lb_grad_xx_2_stencil_update_stream$reg_1_1) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? lb_grad_xx_2_stencil_update_stream$mem_1$mem_rdata : (state->lb_grad_xx_2_stencil_update_stream$reg_1_1));
(state->lb_grad_xx_2_stencil_update_stream$reg_1_2) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? (state->lb_grad_xx_2_stencil_update_stream$reg_1_1) : (state->lb_grad_xx_2_stencil_update_stream$reg_1_2));
(state->lb_grad_xx_2_stencil_update_stream$reg_2_2) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? (state->lb_grad_xx_2_stencil_update_stream$reg_2_1) : (state->lb_grad_xx_2_stencil_update_stream$reg_2_2));
(state->lb_grad_xx_2_stencil_update_stream$reg_2_1) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? lb_grad_xx_2_stencil_update_stream$mem_2$mem_rdata : (state->lb_grad_xx_2_stencil_update_stream$reg_2_1));
(state->lb_padded_2_stencil_update_stream$reg_0_1) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? (state->self_in_0) : (state->lb_padded_2_stencil_update_stream$reg_0_1));
(state->lb_padded_2_stencil_update_stream$mem_1$mem)[ (state->lb_padded_2_stencil_update_stream$mem_1$waddr$reg0) ] = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1)) && /* LOCAL */lb_padded_2_stencil_update_stream_wen_out) ? (state->self_in_0) : (state->lb_padded_2_stencil_update_stream$mem_1$mem)[ (state->lb_padded_2_stencil_update_stream$mem_1$waddr$reg0) ]);
(state->lb_grad_yy_2_stencil_update_stream$reg_0_1) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? /* LOCAL */mul_715_715_716_out : (state->lb_grad_yy_2_stencil_update_stream$reg_0_1));
(state->lb_grad_yy_2_stencil_update_stream$mem_1$mem)[ (state->lb_grad_yy_2_stencil_update_stream$mem_1$waddr$reg0) ] = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1)) && /* LOCAL */lb_grad_yy_2_stencil_update_stream_wen_out) ? /* LOCAL */mul_715_715_716_out : (state->lb_grad_yy_2_stencil_update_stream$mem_1$mem)[ (state->lb_grad_yy_2_stencil_update_stream$mem_1$waddr$reg0) ]);
(state->lb_grad_xy_2_stencil_update_stream$reg_0_1) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? /* LOCAL */mul_691_693_694_out : (state->lb_grad_xy_2_stencil_update_stream$reg_0_1));
(state->lb_grad_xy_2_stencil_update_stream$mem_1$mem)[ (state->lb_grad_xy_2_stencil_update_stream$mem_1$waddr$reg0) ] = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1)) && /* LOCAL */lb_grad_xy_2_stencil_update_stream_wen_out) ? /* LOCAL */mul_691_693_694_out : (state->lb_grad_xy_2_stencil_update_stream$mem_1$mem)[ (state->lb_grad_xy_2_stencil_update_stream$mem_1$waddr$reg0) ]);
(state->lb_grad_xx_2_stencil_update_stream$reg_0_1) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? /* LOCAL */mul_649_649_650_out : (state->lb_grad_xx_2_stencil_update_stream$reg_0_1));
(state->lb_grad_xx_2_stencil_update_stream$mem_1$mem)[ (state->lb_grad_xx_2_stencil_update_stream$mem_1$waddr$reg0) ] = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1)) && /* LOCAL */lb_grad_xx_2_stencil_update_stream_wen_out) ? /* LOCAL */mul_649_649_650_out : (state->lb_grad_xx_2_stencil_update_stream$mem_1$mem)[ (state->lb_grad_xx_2_stencil_update_stream$mem_1$waddr$reg0) ]);
(state->lb_p3_cim_stencil_update_stream$reg_0_1) = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1))) ? /* LOCAL */sub_746_749_750_out : (state->lb_p3_cim_stencil_update_stream$reg_0_1));
(state->lb_p3_cim_stencil_update_stream$mem_1$mem)[ (state->lb_p3_cim_stencil_update_stream$mem_1$waddr$reg0) ] = (((((state->self_clk_last) == 0) && ((state->self_clk) == 1)) && /* LOCAL */lb_p3_cim_stencil_update_stream_wen_out) ? /* LOCAL */sub_746_749_750_out : (state->lb_p3_cim_stencil_update_stream$mem_1$mem)[ (state->lb_p3_cim_stencil_update_stream$mem_1$waddr$reg0) ]);

// ----- Update outputs of sequential elements
lb_padded_2_stencil_update_stream$reg_2_2_out = (state->lb_padded_2_stencil_update_stream$reg_2_2);
lb_padded_2_stencil_update_stream$reg_1_2_out = (state->lb_padded_2_stencil_update_stream$reg_1_2);
lb_padded_2_stencil_update_stream$reg_0_2_out = (state->lb_padded_2_stencil_update_stream$reg_0_2);
lb_padded_2_stencil_update_stream$reg_0_1_out = (state->lb_padded_2_stencil_update_stream$reg_0_1);
lb_padded_2_stencil_update_stream$reg_2_1_out = (state->lb_padded_2_stencil_update_stream$reg_2_1);
lb_padded_2_stencil_update_stream$mem_2$waddr$reg0_out = (state->lb_padded_2_stencil_update_stream$mem_2$waddr$reg0);
lb_padded_2_stencil_update_stream$mem_2$raddr$reg0_out = (state->lb_padded_2_stencil_update_stream$mem_2$raddr$reg0);
lb_padded_2_stencil_update_stream$mem_2$mem_rdata = ((state->lb_padded_2_stencil_update_stream$mem_2$mem)[ (state->lb_padded_2_stencil_update_stream$mem_2$raddr$reg0) ]);
lb_padded_2_stencil_update_stream$reg_1_1_out = (state->lb_padded_2_stencil_update_stream$reg_1_1);
lb_padded_2_stencil_update_stream$mem_1$waddr$reg0_out = (state->lb_padded_2_stencil_update_stream$mem_1$waddr$reg0);
lb_padded_2_stencil_update_stream$mem_1$raddr$reg0_out = (state->lb_padded_2_stencil_update_stream$mem_1$raddr$reg0);
lb_padded_2_stencil_update_stream$mem_1$mem_rdata = ((state->lb_padded_2_stencil_update_stream$mem_1$mem)[ (state->lb_padded_2_stencil_update_stream$mem_1$raddr$reg0) ]);
lb_p3_cim_stencil_update_stream$reg_2_2_out = (state->lb_p3_cim_stencil_update_stream$reg_2_2);
lb_p3_cim_stencil_update_stream$reg_1_2_out = (state->lb_p3_cim_stencil_update_stream$reg_1_2);
lb_p3_cim_stencil_update_stream$reg_0_2_out = (state->lb_p3_cim_stencil_update_stream$reg_0_2);
lb_p3_cim_stencil_update_stream$reg_0_1_out = (state->lb_p3_cim_stencil_update_stream$reg_0_1);
lb_p3_cim_stencil_update_stream$reg_2_1_out = (state->lb_p3_cim_stencil_update_stream$reg_2_1);
lb_p3_cim_stencil_update_stream$mem_2$waddr$reg0_out = (state->lb_p3_cim_stencil_update_stream$mem_2$waddr$reg0);
lb_p3_cim_stencil_update_stream$mem_2$raddr$reg0_out = (state->lb_p3_cim_stencil_update_stream$mem_2$raddr$reg0);
lb_p3_cim_stencil_update_stream$mem_2$mem_rdata = ((state->lb_p3_cim_stencil_update_stream$mem_2$mem)[ (state->lb_p3_cim_stencil_update_stream$mem_2$raddr$reg0) ]);
lb_p3_cim_stencil_update_stream$reg_1_1_out = (state->lb_p3_cim_stencil_update_stream$reg_1_1);
lb_p3_cim_stencil_update_stream$mem_1$waddr$reg0_out = (state->lb_p3_cim_stencil_update_stream$mem_1$waddr$reg0);
lb_p3_cim_stencil_update_stream$mem_1$raddr$reg0_out = (state->lb_p3_cim_stencil_update_stream$mem_1$raddr$reg0);
lb_p3_cim_stencil_update_stream$mem_1$mem_rdata = ((state->lb_p3_cim_stencil_update_stream$mem_1$mem)[ (state->lb_p3_cim_stencil_update_stream$mem_1$raddr$reg0) ]);
lb_grad_yy_2_stencil_update_stream$reg_2_2_out = (state->lb_grad_yy_2_stencil_update_stream$reg_2_2);
lb_grad_yy_2_stencil_update_stream$mem_2$waddr$reg0_out = (state->lb_grad_yy_2_stencil_update_stream$mem_2$waddr$reg0);
lb_grad_yy_2_stencil_update_stream$mem_2$raddr$reg0_out = (state->lb_grad_yy_2_stencil_update_stream$mem_2$raddr$reg0);
lb_grad_yy_2_stencil_update_stream$mem_2$mem_rdata = ((state->lb_grad_yy_2_stencil_update_stream$mem_2$mem)[ (state->lb_grad_yy_2_stencil_update_stream$mem_2$raddr$reg0) ]);
lb_grad_yy_2_stencil_update_stream$mem_1$waddr$reg0_out = (state->lb_grad_yy_2_stencil_update_stream$mem_1$waddr$reg0);
lb_grad_yy_2_stencil_update_stream$mem_1$raddr$reg0_out = (state->lb_grad_yy_2_stencil_update_stream$mem_1$raddr$reg0);
lb_grad_yy_2_stencil_update_stream$mem_1$mem_rdata = ((state->lb_grad_yy_2_stencil_update_stream$mem_1$mem)[ (state->lb_grad_yy_2_stencil_update_stream$mem_1$raddr$reg0) ]);
lb_grad_xy_2_stencil_update_stream$reg_2_2_out = (state->lb_grad_xy_2_stencil_update_stream$reg_2_2);
lb_grad_xy_2_stencil_update_stream$mem_2$waddr$reg0_out = (state->lb_grad_xy_2_stencil_update_stream$mem_2$waddr$reg0);
lb_grad_xy_2_stencil_update_stream$mem_2$raddr$reg0_out = (state->lb_grad_xy_2_stencil_update_stream$mem_2$raddr$reg0);
lb_grad_xy_2_stencil_update_stream$mem_2$mem_rdata = ((state->lb_grad_xy_2_stencil_update_stream$mem_2$mem)[ (state->lb_grad_xy_2_stencil_update_stream$mem_2$raddr$reg0) ]);
lb_grad_xy_2_stencil_update_stream$mem_1$waddr$reg0_out = (state->lb_grad_xy_2_stencil_update_stream$mem_1$waddr$reg0);
lb_grad_xy_2_stencil_update_stream$mem_1$raddr$reg0_out = (state->lb_grad_xy_2_stencil_update_stream$mem_1$raddr$reg0);
lb_grad_xy_2_stencil_update_stream$mem_1$mem_rdata = ((state->lb_grad_xy_2_stencil_update_stream$mem_1$mem)[ (state->lb_grad_xy_2_stencil_update_stream$mem_1$raddr$reg0) ]);
lb_grad_xx_2_stencil_update_stream$reg_2_2_out = (state->lb_grad_xx_2_stencil_update_stream$reg_2_2);
lb_grad_xx_2_stencil_update_stream$mem_2$waddr$reg0_out = (state->lb_grad_xx_2_stencil_update_stream$mem_2$waddr$reg0);
lb_grad_xx_2_stencil_update_stream$mem_2$raddr$reg0_out = (state->lb_grad_xx_2_stencil_update_stream$mem_2$raddr$reg0);
lb_grad_xx_2_stencil_update_stream$mem_2$mem_rdata = ((state->lb_grad_xx_2_stencil_update_stream$mem_2$mem)[ (state->lb_grad_xx_2_stencil_update_stream$mem_2$raddr$reg0) ]);
lb_grad_xx_2_stencil_update_stream$mem_1$waddr$reg0_out = (state->lb_grad_xx_2_stencil_update_stream$mem_1$waddr$reg0);
lb_grad_xx_2_stencil_update_stream$mem_1$raddr$reg0_out = (state->lb_grad_xx_2_stencil_update_stream$mem_1$raddr$reg0);
lb_grad_xx_2_stencil_update_stream$mem_1$mem_rdata = ((state->lb_grad_xx_2_stencil_update_stream$mem_1$mem)[ (state->lb_grad_xx_2_stencil_update_stream$mem_1$raddr$reg0) ]);
lb_grad_yy_2_stencil_update_stream$reg_0_1_out = (state->lb_grad_yy_2_stencil_update_stream$reg_0_1);
lb_grad_yy_2_stencil_update_stream$reg_0_2_out = (state->lb_grad_yy_2_stencil_update_stream$reg_0_2);
lb_grad_yy_2_stencil_update_stream$reg_1_1_out = (state->lb_grad_yy_2_stencil_update_stream$reg_1_1);
lb_grad_yy_2_stencil_update_stream$reg_1_2_out = (state->lb_grad_yy_2_stencil_update_stream$reg_1_2);
lb_grad_yy_2_stencil_update_stream$reg_2_1_out = (state->lb_grad_yy_2_stencil_update_stream$reg_2_1);
lb_grad_xy_2_stencil_update_stream$reg_0_1_out = (state->lb_grad_xy_2_stencil_update_stream$reg_0_1);
lb_grad_xy_2_stencil_update_stream$reg_0_2_out = (state->lb_grad_xy_2_stencil_update_stream$reg_0_2);
lb_grad_xy_2_stencil_update_stream$reg_1_1_out = (state->lb_grad_xy_2_stencil_update_stream$reg_1_1);
lb_grad_xy_2_stencil_update_stream$reg_1_2_out = (state->lb_grad_xy_2_stencil_update_stream$reg_1_2);
lb_grad_xy_2_stencil_update_stream$reg_2_1_out = (state->lb_grad_xy_2_stencil_update_stream$reg_2_1);
lb_grad_xx_2_stencil_update_stream$reg_0_1_out = (state->lb_grad_xx_2_stencil_update_stream$reg_0_1);
lb_grad_xx_2_stencil_update_stream$reg_0_2_out = (state->lb_grad_xx_2_stencil_update_stream$reg_0_2);
lb_grad_xx_2_stencil_update_stream$reg_1_1_out = (state->lb_grad_xx_2_stencil_update_stream$reg_1_1);
lb_grad_xx_2_stencil_update_stream$reg_1_2_out = (state->lb_grad_xx_2_stencil_update_stream$reg_1_2);
lb_grad_xx_2_stencil_update_stream$reg_2_1_out = (state->lb_grad_xx_2_stencil_update_stream$reg_2_1);
 }
// ----- Update combinational logic
lb_padded_2_stencil_update_stream$mem_2$zero_const_out = 0b000000000;
lb_padded_2_stencil_update_stream$mem_2$max_const_out = 0b111100110;
lb_padded_2_stencil_update_stream$mem_2$c1_out = 0b000000001;
lb_padded_2_stencil_update_stream$mem_2$add_w_out = MASK( 9, ((state->lb_padded_2_stencil_update_stream$mem_2$waddr$reg0) + /* LOCAL */lb_padded_2_stencil_update_stream$mem_2$c1_out) );
lb_padded_2_stencil_update_stream$mem_2$add_r_out = MASK( 9, ((state->lb_padded_2_stencil_update_stream$mem_2$raddr$reg0) + /* LOCAL */lb_padded_2_stencil_update_stream$mem_2$c1_out) );
lb_padded_2_stencil_update_stream$mem_1$zero_const_out = 0b000000000;
lb_padded_2_stencil_update_stream_wen_out = 1;
lb_padded_2_stencil_update_stream$mem_1$max_const_out = 0b111100110;
lb_padded_2_stencil_update_stream$mem_1$c1_out = 0b000000001;
lb_padded_2_stencil_update_stream$mem_1$add_w_out = MASK( 9, ((state->lb_padded_2_stencil_update_stream$mem_1$waddr$reg0) + /* LOCAL */lb_padded_2_stencil_update_stream$mem_1$c1_out) );
lb_padded_2_stencil_update_stream$mem_1$add_r_out = MASK( 9, ((state->lb_padded_2_stencil_update_stream$mem_1$raddr$reg0) + /* LOCAL */lb_padded_2_stencil_update_stream$mem_1$c1_out) );
lb_p3_cim_stencil_update_stream$mem_2$zero_const_out = 0b000000000;
lb_p3_cim_stencil_update_stream$mem_2$max_const_out = 0b111100010;
lb_p3_cim_stencil_update_stream$mem_2$c1_out = 0b000000001;
lb_p3_cim_stencil_update_stream$mem_2$add_w_out = MASK( 9, ((state->lb_p3_cim_stencil_update_stream$mem_2$waddr$reg0) + /* LOCAL */lb_p3_cim_stencil_update_stream$mem_2$c1_out) );
lb_p3_cim_stencil_update_stream$mem_2$add_r_out = MASK( 9, ((state->lb_p3_cim_stencil_update_stream$mem_2$raddr$reg0) + /* LOCAL */lb_p3_cim_stencil_update_stream$mem_2$c1_out) );
lb_p3_cim_stencil_update_stream$mem_1$zero_const_out = 0b000000000;
lb_p3_cim_stencil_update_stream_wen_out = 1;
lb_p3_cim_stencil_update_stream$mem_1$max_const_out = 0b111100010;
lb_p3_cim_stencil_update_stream$mem_1$c1_out = 0b000000001;
lb_p3_cim_stencil_update_stream$mem_1$add_w_out = MASK( 9, ((state->lb_p3_cim_stencil_update_stream$mem_1$waddr$reg0) + /* LOCAL */lb_p3_cim_stencil_update_stream$mem_1$c1_out) );
lb_p3_cim_stencil_update_stream$mem_1$add_r_out = MASK( 9, ((state->lb_p3_cim_stencil_update_stream$mem_1$raddr$reg0) + /* LOCAL */lb_p3_cim_stencil_update_stream$mem_1$c1_out) );
lb_grad_yy_2_stencil_update_stream$mem_2$zero_const_out = 0b000000000;
lb_grad_yy_2_stencil_update_stream$mem_2$max_const_out = 0b111100100;
lb_grad_yy_2_stencil_update_stream$mem_2$c1_out = 0b000000001;
lb_grad_yy_2_stencil_update_stream$mem_2$add_w_out = MASK( 9, ((state->lb_grad_yy_2_stencil_update_stream$mem_2$waddr$reg0) + /* LOCAL */lb_grad_yy_2_stencil_update_stream$mem_2$c1_out) );
lb_grad_yy_2_stencil_update_stream$mem_2$add_r_out = MASK( 9, ((state->lb_grad_yy_2_stencil_update_stream$mem_2$raddr$reg0) + /* LOCAL */lb_grad_yy_2_stencil_update_stream$mem_2$c1_out) );
lb_grad_yy_2_stencil_update_stream$mem_1$zero_const_out = 0b000000000;
lb_grad_yy_2_stencil_update_stream_wen_out = 1;
lb_grad_yy_2_stencil_update_stream$mem_1$max_const_out = 0b111100100;
lb_grad_yy_2_stencil_update_stream$mem_1$c1_out = 0b000000001;
lb_grad_yy_2_stencil_update_stream$mem_1$add_w_out = MASK( 9, ((state->lb_grad_yy_2_stencil_update_stream$mem_1$waddr$reg0) + /* LOCAL */lb_grad_yy_2_stencil_update_stream$mem_1$c1_out) );
lb_grad_yy_2_stencil_update_stream$mem_1$add_r_out = MASK( 9, ((state->lb_grad_yy_2_stencil_update_stream$mem_1$raddr$reg0) + /* LOCAL */lb_grad_yy_2_stencil_update_stream$mem_1$c1_out) );
lb_grad_xy_2_stencil_update_stream$mem_2$zero_const_out = 0b000000000;
lb_grad_xy_2_stencil_update_stream$mem_2$max_const_out = 0b111100100;
lb_grad_xy_2_stencil_update_stream$mem_2$c1_out = 0b000000001;
lb_grad_xy_2_stencil_update_stream$mem_2$add_w_out = MASK( 9, ((state->lb_grad_xy_2_stencil_update_stream$mem_2$waddr$reg0) + /* LOCAL */lb_grad_xy_2_stencil_update_stream$mem_2$c1_out) );
lb_grad_xy_2_stencil_update_stream$mem_2$add_r_out = MASK( 9, ((state->lb_grad_xy_2_stencil_update_stream$mem_2$raddr$reg0) + /* LOCAL */lb_grad_xy_2_stencil_update_stream$mem_2$c1_out) );
lb_grad_xy_2_stencil_update_stream$mem_1$zero_const_out = 0b000000000;
lb_grad_xy_2_stencil_update_stream_wen_out = 1;
lb_grad_xy_2_stencil_update_stream$mem_1$max_const_out = 0b111100100;
lb_grad_xy_2_stencil_update_stream$mem_1$c1_out = 0b000000001;
lb_grad_xy_2_stencil_update_stream$mem_1$add_w_out = MASK( 9, ((state->lb_grad_xy_2_stencil_update_stream$mem_1$waddr$reg0) + /* LOCAL */lb_grad_xy_2_stencil_update_stream$mem_1$c1_out) );
lb_grad_xy_2_stencil_update_stream$mem_1$add_r_out = MASK( 9, ((state->lb_grad_xy_2_stencil_update_stream$mem_1$raddr$reg0) + /* LOCAL */lb_grad_xy_2_stencil_update_stream$mem_1$c1_out) );
lb_grad_xx_2_stencil_update_stream$mem_2$zero_const_out = 0b000000000;
lb_grad_xx_2_stencil_update_stream$mem_2$max_const_out = 0b111100100;
lb_grad_xx_2_stencil_update_stream$mem_2$c1_out = 0b000000001;
lb_grad_xx_2_stencil_update_stream$mem_2$add_w_out = MASK( 9, ((state->lb_grad_xx_2_stencil_update_stream$mem_2$waddr$reg0) + /* LOCAL */lb_grad_xx_2_stencil_update_stream$mem_2$c1_out) );
lb_grad_xx_2_stencil_update_stream$mem_2$add_r_out = MASK( 9, ((state->lb_grad_xx_2_stencil_update_stream$mem_2$raddr$reg0) + /* LOCAL */lb_grad_xx_2_stencil_update_stream$mem_2$c1_out) );
lb_grad_xx_2_stencil_update_stream$mem_1$zero_const_out = 0b000000000;
lb_grad_xx_2_stencil_update_stream_wen_out = 1;
lb_grad_xx_2_stencil_update_stream$mem_1$max_const_out = 0b111100100;
lb_grad_xx_2_stencil_update_stream$mem_1$c1_out = 0b000000001;
lb_grad_xx_2_stencil_update_stream$mem_1$add_w_out = MASK( 9, ((state->lb_grad_xx_2_stencil_update_stream$mem_1$waddr$reg0) + /* LOCAL */lb_grad_xx_2_stencil_update_stream$mem_1$c1_out) );
lb_grad_xx_2_stencil_update_stream$mem_1$add_r_out = MASK( 9, ((state->lb_grad_xx_2_stencil_update_stream$mem_1$raddr$reg0) + /* LOCAL */lb_grad_xx_2_stencil_update_stream$mem_1$c1_out) );
sub_686_688_689_out = ((((((state->lb_padded_2_stencil_update_stream$reg_0_2) - (state->lb_padded_2_stencil_update_stream$reg_2_2)) + ((state->lb_padded_2_stencil_update_stream$reg_0_1) * 0b0000000000000010)) - ((state->lb_padded_2_stencil_update_stream$reg_2_1) * 0b0000000000000010)) + (state->self_in_0)) - lb_padded_2_stencil_update_stream$mem_2$mem_rdata);
mul_715_715_716_out = (/* LOCAL */sub_686_688_689_out * /* LOCAL */sub_686_688_689_out);
ashr_737_739_741_out = ((((((((((0b0000000000000000 + /* LOCAL */mul_715_715_716_out) + (state->lb_grad_yy_2_stencil_update_stream$reg_2_1)) + lb_grad_yy_2_stencil_update_stream$mem_2$mem_rdata) + (state->lb_grad_yy_2_stencil_update_stream$reg_1_2)) + (state->lb_grad_yy_2_stencil_update_stream$reg_1_1)) + lb_grad_yy_2_stencil_update_stream$mem_1$mem_rdata) + (state->lb_grad_yy_2_stencil_update_stream$reg_0_2)) + (state->lb_grad_yy_2_stencil_update_stream$reg_0_1)) + /* LOCAL */mul_715_715_716_out) >> 0b0000000000000111);
add_644_646_647_out = (((((lb_padded_2_stencil_update_stream$mem_2$mem_rdata - (state->lb_padded_2_stencil_update_stream$reg_2_2)) - ((state->lb_padded_2_stencil_update_stream$reg_1_2) * 0b0000000000000010)) + (lb_padded_2_stencil_update_stream$mem_1$mem_rdata * 0b0000000000000010)) - (state->lb_padded_2_stencil_update_stream$reg_0_2)) + (state->self_in_0));
mul_691_693_694_out = (/* LOCAL */add_644_646_647_out * /* LOCAL */sub_686_688_689_out);
ashr_738_739_744_out = ((((((((((0b0000000000000000 + /* LOCAL */mul_691_693_694_out) + (state->lb_grad_xy_2_stencil_update_stream$reg_2_1)) + lb_grad_xy_2_stencil_update_stream$mem_2$mem_rdata) + (state->lb_grad_xy_2_stencil_update_stream$reg_1_2)) + (state->lb_grad_xy_2_stencil_update_stream$reg_1_1)) + lb_grad_xy_2_stencil_update_stream$mem_1$mem_rdata) + (state->lb_grad_xy_2_stencil_update_stream$reg_0_2)) + (state->lb_grad_xy_2_stencil_update_stream$reg_0_1)) + /* LOCAL */mul_691_693_694_out) >> 0b0000000000000111);
mul_649_649_650_out = (/* LOCAL */add_644_646_647_out * /* LOCAL */add_644_646_647_out);
ashr_736_739_740_out = ((((((((((0b0000000000000000 + /* LOCAL */mul_649_649_650_out) + (state->lb_grad_xx_2_stencil_update_stream$reg_2_1)) + lb_grad_xx_2_stencil_update_stream$mem_2$mem_rdata) + (state->lb_grad_xx_2_stencil_update_stream$reg_1_2)) + (state->lb_grad_xx_2_stencil_update_stream$reg_1_1)) + lb_grad_xx_2_stencil_update_stream$mem_1$mem_rdata) + (state->lb_grad_xx_2_stencil_update_stream$reg_0_2)) + (state->lb_grad_xx_2_stencil_update_stream$reg_0_1)) + /* LOCAL */mul_649_649_650_out) >> 0b0000000000000111);
add_740_741_742_out = (/* LOCAL */ashr_736_739_740_out + /* LOCAL */ashr_737_739_741_out);
sub_746_749_750_out = (((/* LOCAL */ashr_736_739_740_out * /* LOCAL */ashr_737_739_741_out) - (/* LOCAL */ashr_738_739_744_out * /* LOCAL */ashr_738_739_744_out)) - ((/* LOCAL */add_740_741_742_out * /* LOCAL */add_740_741_742_out) >> 0b0000000000000100));
smax_752_753_754$max_mux_out = (MASK( 1, ((int16_t) (/* LOCAL */sub_746_749_750_out)) >= ((int16_t) ((state->lb_p3_cim_stencil_update_stream$reg_2_1))) ) ? /* LOCAL */sub_746_749_750_out : (state->lb_p3_cim_stencil_update_stream$reg_2_1));
smax_754_755_756$max_mux_out = (MASK( 1, ((int16_t) (/* LOCAL */smax_752_753_754$max_mux_out)) >= ((int16_t) (lb_p3_cim_stencil_update_stream$mem_2$mem_rdata)) ) ? /* LOCAL */smax_752_753_754$max_mux_out : lb_p3_cim_stencil_update_stream$mem_2$mem_rdata);
smax_756_757_758$max_mux_out = (MASK( 1, ((int16_t) (/* LOCAL */smax_754_755_756$max_mux_out)) >= ((int16_t) ((state->lb_p3_cim_stencil_update_stream$reg_1_2))) ) ? /* LOCAL */smax_754_755_756$max_mux_out : (state->lb_p3_cim_stencil_update_stream$reg_1_2));
smax_758_759_760$max_mux_out = (MASK( 1, ((int16_t) (/* LOCAL */smax_756_757_758$max_mux_out)) >= ((int16_t) (lb_p3_cim_stencil_update_stream$mem_1$mem_rdata)) ) ? /* LOCAL */smax_756_757_758$max_mux_out : lb_p3_cim_stencil_update_stream$mem_1$mem_rdata);
smax_760_761_762$max_mux_out = (MASK( 1, ((int16_t) (/* LOCAL */smax_758_759_760$max_mux_out)) >= ((int16_t) ((state->lb_p3_cim_stencil_update_stream$reg_0_2))) ) ? /* LOCAL */smax_758_759_760$max_mux_out : (state->lb_p3_cim_stencil_update_stream$reg_0_2));
smax_762_763_764$max_mux_out = (MASK( 1, ((int16_t) (/* LOCAL */smax_760_761_762$max_mux_out)) >= ((int16_t) ((state->lb_p3_cim_stencil_update_stream$reg_0_1))) ) ? /* LOCAL */smax_760_761_762$max_mux_out : (state->lb_p3_cim_stencil_update_stream$reg_0_1));
(state->self_out) = (MASK( 1, (MASK( 1, ((MASK( 1, ((int16_t) (/* LOCAL */smax_762_763_764$max_mux_out)) >= ((int16_t) (/* LOCAL */sub_746_749_750_out)) ) ? /* LOCAL */smax_762_763_764$max_mux_out : /* LOCAL */sub_746_749_750_out) < (state->lb_p3_cim_stencil_update_stream$reg_1_1)) ) & MASK( 1, (0b0000000001100100 <= (state->lb_p3_cim_stencil_update_stream$reg_1_1)) )) ) ? 0b0000000000000000 : 0b0000000011111111);
}

void simulate( circuit_state* state ) {
simulate_0( state );
}
